server:
  port: 8189
  servlet:
    context-path: /lib
spring:
  application:
    name: graduate-project
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=graduate_project_library
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
    open-in-view: false